"""Token Streaming Pipeline — Never wait for the model to finish.

Generate Token → Immediately Display → Generate Next Token → Continue.
Everything downstream consumes streamed output for minimum perceived latency.
"""
import asyncio
import logging
import threading
import time
from collections import deque
from collections.abc import AsyncGenerator, Callable
from dataclasses import dataclass
from typing import Any

logger = logging.getLogger("ai_runtime.token_streaming")


@dataclass
class TokenEvent:
    """A single token from the streaming pipeline."""
    token: str
    index: int
    timestamp: float = 0.0
    token_ms: float = 0.0  # time since previous token
    is_final: bool = False

    def __post_init__(self):
        if self.timestamp == 0.0:
            self.timestamp = time.time()


class TokenStreamingPipeline:
    """Real-time token streaming with downstream consumption.

    Pipeline stages:
    1. Token generated by LLM
    2. Token enriched (metadata, timing)
    3. Token forwarded to consumers (TTS, display, buffer)
    4. Token cached for prediction
    """

    def __init__(self, max_tokens: int = 4096):
        self._consumers: list[Callable] = []
        self._token_buffer: deque = deque(maxlen=max_tokens)
        self._prefix_buffer: list[str] = []
        self._lock = threading.Lock()
        self._stats = {
            "total_tokens": 0,
            "total_ms": 0.0,
            "avg_token_ms": 0.0,
            "tokens_per_second": 0.0,
            "first_token_ms": 0.0,
            "stream_count": 0,
        }
        self._stream_start = 0.0
        self._last_token_time = 0.0

    def register_consumer(self, callback: Callable) -> None:
        """Register a downstream consumer (e.g., TTS, display)."""
        self._consumers.append(callback)

    async def stream(self, token_generator: AsyncGenerator[str, None],
                     response_id: str = "") -> dict[str, Any]:
        """Stream tokens from an async generator, forwarding to all consumers."""
        self._stream_start = time.time()
        self._last_token_time = self._stream_start
        tokens = []
        first_token_ms = 0.0

        async for token_text in token_generator:
            now = time.time()
            token_ms = (now - self._last_token_time) * 1000

            if not tokens:
                first_token_ms = (now - self._stream_start) * 1000

            event = TokenEvent(
                token=token_text,
                index=len(tokens),
                token_ms=token_ms,
            )
            tokens.append(event)
            self._token_buffer.append(token_text)
            self._prefix_buffer.append(token_text)

            # Notify all consumers
            for consumer in self._consumers:
                try:
                    result = consumer(event)
                    if asyncio.iscoroutine(result):
                        asyncio.get_event_loop().create_task(result)
                except Exception as e:
                    logger.debug("Consumer error: %s", e)

            self._last_token_time = now

        # Final token
        total_ms = (time.time() - self._stream_start) * 1000
        tps = len(tokens) / max(total_ms / 1000, 0.001)

        self._stats["total_tokens"] += len(tokens)
        self._stats["total_ms"] += total_ms
        self._stats["avg_token_ms"] = self._stats["total_ms"] / max(self._stats["total_tokens"], 1)
        self._stats["tokens_per_second"] = tps
        self._stats["first_token_ms"] = first_token_ms
        self._stats["stream_count"] += 1

        return {
            "tokens": len(tokens),
            "total_ms": round(total_ms, 1),
            "first_token_ms": round(first_token_ms, 1),
            "tokens_per_second": round(tps, 1),
            "response_id": response_id,
        }

    def get_prefix(self, length: int = 10) -> str:
        """Get the last N tokens as a prefix string."""
        with self._lock:
            return "".join(list(self._prefix_buffer)[-length:])

    def get_recent_tokens(self, count: int = 20) -> list[str]:
        with self._lock:
            return list(self._token_buffer)[-count:]

    def get_stats(self) -> dict[str, Any]:
        return dict(self._stats)


_streaming_pipeline_instance: TokenStreamingPipeline | None = None


def get_token_streaming_pipeline() -> TokenStreamingPipeline:
    global _streaming_pipeline_instance
    if _streaming_pipeline_instance is None:
        _streaming_pipeline_instance = TokenStreamingPipeline()
    return _streaming_pipeline_instance
