#!/usr/bin/env python3
"""JARVIS Free Setup — configure JARVIS to run 100% free.

Walks through getting free API keys from each provider and writes them
to config/.env. No credit card required for any of these.

Usage:
    python scripts/setup_free.py

Free providers included (sorted by quality):
    1. Groq          — groq.com          (14,400 req/day, fastest inference)
    2. Google Gemini — aistudio.google.com (1,500 req/day, best reasoning)
    3. Cerebras      — cloud.cerebras.ai (1,000 req/day, ultra-fast)
    4. DeepSeek      — platform.deepseek.com (cheap, excellent coding)
    5. OpenRouter    — openrouter.ai     (free models available)
    6. Mistral       — console.mistral.ai (500 req/day)
    7. HuggingFace   — huggingface.co    (free inference API)
    8. Ollama        — ollama.com        (local, unlimited, no API key)
"""

import sys
import os
from pathlib import Path

CONFIG_DIR = Path(__file__).resolve().parent.parent / "config"
DOT_ENV = CONFIG_DIR / ".env"


def _read_existing() -> dict:
    """Read existing .env file."""
    env = {}
    if DOT_ENV.exists():
        for line in DOT_ENV.read_text(encoding="utf-8").splitlines():
            line = line.strip()
            if not line or line.startswith("#") or "=" not in line:
                continue
            key, _, val = line.partition("=")
            env[key.strip()] = val.strip().strip("\"'")
    return env


def _write_env(env: dict) -> None:
    """Write env dict back to .env."""
    lines = [
        "# JARVIS MK-X API Keys",
        "# Generated by scripts/setup_free.py",
        "# All providers listed here offer free tiers — no credit card required.",
        "",
    ]

    sections = {
        "Groq (fastest, free: 14,400 req/day)": ["GROQ_API_KEY"],
        "Google Gemini (best reasoning, free: 1,500 req/day)": ["GEMINI_API_KEY"],
        "Cerebras (ultra-fast, free: 1,000 req/day)": ["CEREBRAS_API_KEY"],
        "DeepSeek (excellent coding, very cheap)": ["DEEPSEEK_API_KEY"],
        "OpenRouter (free model access)": ["OPENROUTER_API_KEY"],
        "Mistral (free: 500 req/day)": ["MISTRAL_API_KEY"],
        "HuggingFace (free inference API)": ["HF_API_KEY"],
    }

    for section_name, keys in sections.items():
        lines.append(f"# {section_name}")
        for key in keys:
            val = env.get(key, "")
            if val:
                lines.append(f'{key}={val}')
            else:
                lines.append(f"# {key}=")
        lines.append("")

    DOT_ENV.write_text("\n".join(lines) + "\n", encoding="utf-8")


def _prompt_key(name: str, url: str, help_text: str, existing: str) -> str:
    """Prompt user for an API key."""
    if existing:
        masked = existing[:4] + "..." + existing[-4:] if len(existing) > 8 else "***"
        print(f"  [OK] {name}: {masked}")
        change = input(f"      Change? (y/N): ").strip().lower()
        if change != "y":
            return existing

    print(f"\n  {name}")
    print(f"  URL: {url}")
    print(f"  {help_text}")
    key = input(f"  Enter {name} (or press Enter to skip): ").strip()
    return key


def main():
    print("=" * 60)
    print("  JARVIS MK-X Free Setup")
    print("  Configure JARVIS to run 100% free")
    print("=" * 60)

    existing = _read_existing()
    new_env = dict(existing)

    # Provider signup URLs and help text
    providers = [
        (
            "GROQ_API_KEY",
            "https://console.groq.com/keys",
            "Sign up -> API Keys -> Create API Key",
        ),
        (
            "GEMINI_API_KEY",
            "https://aistudio.google.com/apikey",
            "Sign in -> Get API Key -> Create Key",
        ),
        (
            "CEREBRAS_API_KEY",
            "https://cloud.cerebras.ai/",
            "Sign up -> API Keys -> Generate Key",
        ),
        (
            "DEEPSEEK_API_KEY",
            "https://platform.deepseek.com/api_keys",
            "Sign up -> API Keys -> Create Key",
        ),
        (
            "OPENROUTER_API_KEY",
            "https://openrouter.ai/keys",
            "Sign up -> Keys -> Create Key",
        ),
        (
            "MISTRAL_API_KEY",
            "https://console.mistral.ai/api-keys/",
            "Sign up -> API Keys -> Create new key",
        ),
        (
            "HF_API_KEY",
            "https://huggingface.co/settings/tokens",
            "Sign up -> Access Tokens -> Create new token",
        ),
    ]

    print("\nYou need at least ONE provider to run JARVIS.")
    print("Groq + Gemini is the recommended combo (fastest + smartest).\n")

    for env_key, url, help_text in providers:
        existing_val = existing.get(env_key, "")
        val = _prompt_key(env_key, url, help_text, existing_val)
        if val:
            new_env[env_key] = val

    _write_env(new_env)

    # Check Ollama
    print("\n  OLLAMA (local, unlimited, free)")
    print("  URL: https://ollama.com/download")
    try:
        import subprocess
        result = subprocess.run(["ollama", "--version"], capture_output=True, text=True, timeout=5)
        if result.returncode == 0:
            print(f"  [OK] Ollama installed: {result.stdout.strip()}")
        else:
            print("  [!!] Ollama not found — install from https://ollama.com/download")
    except (FileNotFoundError, subprocess.TimeoutExpired):
        print("  [!!] Ollama not found — install from https://ollama.com/download")

    # Summary
    configured = sum(1 for k, _, _ in providers if new_env.get(k))
    print(f"\n{'=' * 60}")
    print(f"  Setup complete! {configured}/{len(providers)} providers configured.")
    print()

    if configured == 0:
        print("  WARNING: No API keys configured. JARVIS needs at least one provider.")
        print("  Install Ollama for fully local, offline usage.")
    elif configured <= 2:
        print("  Good start! JARVIS will work with these providers.")
        print("  Add more for better fallback coverage.")
    else:
        print("  Excellent! JARVIS has robust fallback coverage.")

    print()
    print("  Run JARVIS: python -m cli")
    print(f"{'=' * 60}")


if __name__ == "__main__":
    main()
